# Generated by Django 3.1.1 on 2020-10-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_joining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joining',
        ),
    ]
