# Generated by Django 3.1.1 on 2020-10-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='download.png', upload_to='profileimages'),
        ),
    ]
