# Generated by Django 3.1.1 on 2020-10-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201003_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('SG', 'Single'), ('MR', 'Married'), ('CM', 'Complicated'), ('OP', 'Open-Relationship')], max_length=200, null=True),
        ),
    ]
