# Generated by Django 3.1.1 on 2020-10-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Single', 'SG'), ('Married', 'MR'), ('Complicated', 'CM'), ('Open-Relationship', 'OP')], max_length=200, null=True),
        ),
    ]
