# Generated by Django 3.1.1 on 2020-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201003_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Complicated', 'Complicated'), ('Open-Relationship', 'Open-Relationship')], max_length=200, null=True),
        ),
    ]
