# Generated by Django 3.1.1 on 2020-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_blogcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='sno',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
